#!/usr/bin/env python3
"""Generate clk_tables.h from the ZCU111 TICS Pro register exports.

LMK04208 (U90): the stock ZCU111 file sets every CLKoutX_DIV to 24
(2949.12 MHz / 24 = 122.88 MHz).  OUT0 (SYSREF_FPGA -> PL) and OUT1
(SYSREF_RFSOC -> DAC tile 228 analog SYSREF) must be a slow SYSREF for
multi-tile sync, so their dividers are changed to 384 -> 7.68 MHz.
Register format (LMK04208 datasheet SNAS684 table 15):
    R0..R5 : [31] PD  [29:28] ADLY_SEL  [27:18] DDLY  [17] RESET/PD
             [16] HS  [15:5] CLKoutX_DIV  [4:0] address
LMX2594 (U102/U103/U104): used unchanged (245.76 MHz on OUTA and OUTB).

usage: gen_clk_tables.py <lmk.txt> <lmx.txt> > clk_tables.h
"""
import re
import sys

SYSREF_DIV = 384          # 2949.12 MHz / 384 = 7.68 MHz
SYSREF_OUTPUTS = (0, 1)   # CLKout0 -> SYSREF_FPGA, CLKout1 -> SYSREF_RFSOC


def read_tics(fname):
    regs = []
    for line in open(fname):
        m = re.match(r"\s*R(\d+)(\s*\(INIT\))?\s+0x([0-9A-Fa-f]+)", line)
        if m:
            regs.append((int(m.group(1)), int(m.group(3), 16), bool(m.group(2))))
    if not regs:
        raise SystemExit(f"no registers found in {fname}")
    return regs


def patch_lmk(regs):
    out = []
    for n, v, init in regs:
        if not init and n in SYSREF_OUTPUTS:
            assert v & 0x1F == n, "address field mismatch"
            v = (v & ~(0x7FF << 5)) | (SYSREF_DIV << 5)
        out.append((n, v, init))
    return out


def emit(name, regs, fname, note):
    print(f"/* {note}\n * source: {fname} */")
    print(f"static const uint32_t {name}[] = {{")
    for n, v, init in regs:
        tag = " (INIT)" if init else ""
        print(f"    0x{v:08X},  /* R{n}{tag} */")
    print("};")
    print(f"#define {name.upper()}_LEN (sizeof({name}) / sizeof({name}[0]))\n")


def main():
    lmk_f, lmx_f = sys.argv[1], sys.argv[2]
    lmk = patch_lmk(read_tics(lmk_f))
    lmx = read_tics(lmx_f)
    # sanity: LMK R11 must enable SYNC so the SYSREF dividers can be aligned
    r11 = [v for n, v, i in lmk if n == 11][0]
    assert r11 & (1 << 26), "EN_SYNC not set in LMK R11"
    print("/* Generated by gen_clk_tables.py - do not edit */")
    print("#ifndef CLK_TABLES_H\n#define CLK_TABLES_H\n#include <stdint.h>\n")
    print(f"#define LMK_R11_VALUE 0x{r11:08X}u\n")
    emit("lmk04208_regs", lmk, lmk_f,
         "LMK04208 U90: VCO 2949.12 MHz, OUT2/3/4 122.88 MHz, "
         f"OUT0/OUT1 SYSREF 7.68 MHz (DIV {SYSREF_DIV})")
    emit("lmx2594_regs", lmx, lmx_f,
         "LMX2594 U102/U103/U104: 122.88 MHz ref, OSC_2X, N=32, "
         "VCO 7864.32 MHz, CHDIV 32 -> 245.76 MHz on OUTA/OUTB")
    print("#endif")


if __name__ == "__main__":
    main()
