/*
 * pl.c - trigger/capture core, MMCM control and DMA event readout
 *
 * IMPORTANT: the trigger core and the DMA data path run on clk_1x, which is
 * generated by the MMCM from the LMK04208 PL reference.  Never touch the
 * trigger registers before pl_mmcm_start() succeeded - an AXI access to an
 * unclocked slave hangs the interconnect.
 */
#include "pl.h"

#include <errno.h>
#include <string.h>
#include <time.h>
#include <unistd.h>

#include "log.h"
#include "pl_regs.h"
#include "protocol.h"

static uint64_t now_us(void)
{
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (uint64_t)ts.tv_sec * 1000000u + (uint64_t)ts.tv_nsec / 1000u;
}

int pl_open(struct pl *p)
{
    memset(p, 0, sizeof *p);
    p->spec.fd = -1;            /* opened later by spec_init() */
    if (hw_open(&p->gpio, GPIO_BASE, 0x1000) < 0 ||
        hw_open(&p->trig, TRIG_BASE, 0x1000) < 0 ||
        hw_open(&p->dma,  DMA_BASE,  0x1000) < 0 ||
        hw_open(&p->buf,  DMABUF_BASE, DMABUF_SIZE) < 0) {
        pl_close(p);
        return -1;
    }
    return 0;
}

void pl_close(struct pl *p)
{
    hw_close(&p->spec);
    hw_close(&p->buf);
    hw_close(&p->dma);
    hw_close(&p->trig);
    hw_close(&p->gpio);
}

int pl_mmcm_locked(struct pl *p)
{
    return hw_rd(&p->gpio, GPIO2_DATA) & 1u;
}

int pl_mmcm_start(struct pl *p, int timeout_ms)
{
    hw_wr(&p->gpio, GPIO_TRI, 0);          /* channel 1 = output */
    hw_wr(&p->gpio, GPIO_DATA, 1);         /* assert MMCM reset  */
    usleep(1000);
    hw_wr(&p->gpio, GPIO_DATA, 0);
    uint64_t t0 = now_us();
    while (!pl_mmcm_locked(p)) {
        if (now_us() - t0 > (uint64_t)timeout_ms * 1000u) {
            LOGE("pl: MMCM did not lock - no 122.88 MHz on FPGA_REFCLK_OUT (AL16/AL15)?");
            return -1;
        }
        usleep(1000);
    }
    usleep(10000);                         /* proc_sys_reset release */
    LOGI("pl: MMCM locked (clk_2x 491.52 MHz, clk_1x 245.76 MHz, clk_spec 122.88 MHz)");
    return 0;
}

static void dma_reset(struct pl *p)
{
    hw_wr(&p->dma, DMA_S2MM_DMACR, DMACR_RESET);
    for (int i = 0; i < 1000 && (hw_rd(&p->dma, DMA_S2MM_DMACR) & DMACR_RESET); i++)
        usleep(10);
    hw_wr(&p->dma, DMA_S2MM_DMACR, DMACR_RS);
}

int pl_core_init(struct pl *p)
{
    uint32_t id = hw_rd(&p->trig, TR_ID);
    if (id != TR_ID_VALUE) {
        LOGE("pl: trigger core ID 0x%08x != 0x%08x (wrong bitstream?)", id, TR_ID_VALUE);
        return -1;
    }
    uint32_t ver = hw_rd(&p->trig, TR_VERSION);
    p->nbanks = (int)(ver & 0xFF);
    LOGI("pl: trigger core v%u.%u, %d capture banks",
             ver >> 16, (ver >> 8) & 0xFF, p->nbanks);
    p->ctrl_levels = 0;
    hw_wr(&p->trig, TR_CTRL, CTRL_TS_RESET | CTRL_FLUSH | CTRL_CNT_CLEAR);
    dma_reset(p);
    return 0;
}

static void ctrl_write(struct pl *p, uint32_t pulses)
{
    hw_wr(&p->trig, TR_CTRL, p->ctrl_levels | pulses);
}

void pl_apply_config(struct pl *p, const struct luna_config *c)
{
    for (int i = 0; i < LUNA_NCH; i++)
        hw_wr(&p->trig, TR_THRESH(i), c->thresh[i]);
    hw_wr(&p->trig, TR_MODE, (uint32_t)c->mode_anti);
    hw_wr(&p->trig, TR_COINC_N, (uint32_t)c->coinc_n);
    hw_wr(&p->trig, TR_WINDOW, (uint32_t)c->window);
    hw_wr(&p->trig, TR_CH_MASK, c->ch_mask);
    if ((int)(hw_rd(&p->trig, TR_CAP_LEN)) != c->cap_len) {
        /* a new length needs a fresh pre-trigger fill: flush the banks
         * (events already captured are discarded) */
        hw_wr(&p->trig, TR_CAP_LEN, (uint32_t)c->cap_len);
        ctrl_write(p, CTRL_FLUSH);
    }
}

void pl_arm(struct pl *p, int arm)
{
    if (arm)
        p->ctrl_levels |= CTRL_ARM | CTRL_IRQ_EN;
    else
        p->ctrl_levels &= ~CTRL_ARM;
    p->ctrl_levels |= CTRL_IRQ_EN;
    ctrl_write(p, 0);
}

void pl_soft_trigger(struct pl *p)
{
    ctrl_write(p, CTRL_SOFT_TRIG);
}

uint32_t pl_status(struct pl *p)
{
    return hw_rd(&p->trig, TR_STATUS);
}

uint64_t pl_timestamp(struct pl *p)
{
    uint32_t lo = hw_rd(&p->trig, TR_TS_LO);   /* latches TS_HI */
    uint32_t hi = hw_rd(&p->trig, TR_TS_HI);
    return ((uint64_t)hi << 32) | lo;
}

long pl_read_event(struct pl *p, void *dst, size_t max)
{
    uint32_t st = pl_status(p);
    if (ST_NFULL(st) == 0)
        return 0;
    if (st & ST_RD_BUSY) {
        LOGW("pl: readout already busy");
        return -1;
    }

    /* arm the DMA first, then start the stream */
    hw_wr(&p->dma, DMA_S2MM_DMASR, DMASR_IOC_IRQ | DMASR_ERR_IRQ);
    hw_wr(&p->dma, DMA_S2MM_DMACR, DMACR_RS);
    hw_wr(&p->dma, DMA_S2MM_DA, DMABUF_BASE);
    hw_wr(&p->dma, DMA_S2MM_LENGTH, DMABUF_SIZE);
    hw_wr(&p->trig, TR_READOUT, 1);

    uint64_t t0 = now_us();
    uint32_t sr;
    for (;;) {
        sr = hw_rd(&p->dma, DMA_S2MM_DMASR);
        if (sr & (DMASR_IOC_IRQ | DMASR_ERR_MASK))
            break;
        if (now_us() - t0 > 100000) {
            LOGE("pl: DMA timeout (DMASR 0x%08x, STATUS 0x%08x)", sr, pl_status(p));
            dma_reset(p);
            return -1;
        }
    }
    if (sr & DMASR_ERR_MASK) {
        LOGE("pl: DMA error, DMASR 0x%08x", sr);
        dma_reset(p);
        return -1;
    }
    uint32_t bytes = hw_rd(&p->dma, DMA_S2MM_LENGTH);
    hw_wr(&p->dma, DMA_S2MM_DMASR, DMASR_IOC_IRQ);

    /* wait until the core has seen the end of the stream */
    while (pl_status(p) & ST_RD_BUSY) {
        if (now_us() - t0 > 200000) {
            LOGE("pl: readout did not finish");
            return -1;
        }
    }

    long ret = -1;
    const struct luna_event_hdr *h = (const void *)p->buf.regs;
    if (bytes > max || bytes < sizeof *h) {
        LOGE("pl: event of %u bytes does not fit (max %zu)", bytes, max);
    } else if (h->magic != LUNA_EVENT_MAGIC ||
               bytes != sizeof *h + (size_t)h->n_samples * LUNA_NCH * 2) {
        LOGE("pl: corrupt event (magic 0x%08x, %u bytes, n_samples %u)",
                h->magic, bytes, h->n_samples);
    } else {
        hw_copy_from_io(dst, p->buf.regs, bytes);
        ret = (long)bytes;
    }
    hw_wr(&p->trig, TR_RELEASE, 1);           /* free the bank */
    return ret;
}

void pl_counters(struct pl *p, uint32_t *trig, uint32_t *lost, uint32_t *sysref)
{
    *trig = hw_rd(&p->trig, TR_TRIG_COUNT);
    *lost = hw_rd(&p->trig, TR_LOST_COUNT);
    *sysref = hw_rd(&p->trig, TR_SYSREF_CNT);
}

void pl_hit_counts(struct pl *p, uint32_t cnt[8])
{
    for (int i = 0; i < LUNA_NCH; i++)
        cnt[i] = hw_rd(&p->trig, TR_HITCNT(i));
}

void pl_peaks(struct pl *p, uint16_t peak[8])
{
    for (int i = 0; i < LUNA_NCH; i++)
        peak[i] = (uint16_t)hw_rd(&p->trig, TR_PEAK(i));
}
